'use strict';

//mui
export const SET_THEME = 'SET_THEME';
export const SET_DEVICE_SIZE = 'SET_DEVICE_SIZE';

//loading
export const LOADING_ON = 'LOADING_ON';
export const LOADING_OFF = 'LOADING_OFF';

//toast
export const OPEN_TOAST = 'OPEN_TOAST';
export const CLOSE_TOAST = 'CLOSE_TOAST';

//side_bar
export const SIDE_BAR_SHOW = 'SIDE_BAR_SHOW';
export const SIDE_BAR_HIDE = 'SIDE_BAR_HIDE';



//获取手机验证码
export const GET_AUTH_CODE = 'GET_AUTH_CODE';     
export const GET_AUTH_CODE_SUCCESS = 'GET_AUTH_CODE_SUCCESS';
export const GET_AUTH_CODE_FAILURE = 'GET_AUTH_CODE_FAILURE';

//signin
export const SIGNIN = 'SIGNIN';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';
export const SIGNIN_CLEAN = 'SIGNIN_CLEAN';
export const SIGNIN_TYPE_CLEAN = 'SIGNIN_TYPE_CLEAN';
//signout
export const SIGNOUT = 'SIGNOUT';

//menus
// export const MENU_CHANGE = 'MENU_CHANGE';

//remember me
export const REMEMBER_ME = 'REMEMBER_ME';
//auto signin
export const AUTO_SIGNIN = 'AUTO_SIGNIN';

//user
export const USER_RESTORE = 'USER_RESTORE'
export const USER_TYPE_CLEAN = 'USER_TYPE_CLEAN';

//users
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

//mansion
export const GET_HOUSE_LAYOUT_PATTERNS_SUCCESS = 'GET_HOUSE_LAYOUT_PATTERNS_SUCCESS';
export const GET_MANSIONS_SUCCESS = 'GET_MANSIONS_SUCCESS';
export const GET_MANSIONS_INFO_SUCCESS = 'GET_MANSIONS_INFO_SUCCESS';
export const ADD_MANSION_SUCCESS = 'ADD_MANSION_SUCCESS';
export const DELETE_MANSION_SUCCESS = 'DELETE_MANSION_SUCCESS';
export const IMPORT_HISTORY_VERSION_DATA_SUCCESS = 'IMPORT_HISTORY_VERSION_DATA_SUCCESS';

export const SAVE_MANSION_BASE_SUCCESS = 'SAVE_MANSION_BASE_SUCCESS';
export const SAVE_HOUSE_LAYOUTS_SUCCESS = 'SAVE_HOUSE_LAYOUTS_SUCCESS';
export const SAVE_HOUSES_SUCCESS = 'SAVE_HOUSES_SUCCESS';
export const SAVE_FLOOR_SUCCESS = 'SAVE_FLOOR_SUCCESS';
export const SAVE_MANAGERS_INFO_SUCCESS = 'SAVE_MANAGERS_INFO_SUCCESS';


//出租房
export const HOUSE_CHECK_IN_SUCCESS = 'HOUSE_CHECK_IN_SUCCESS';
export const HOUSE_PAY_RENT_SUCCESS = 'HOUSE_PAY_RENT_SUCCESS';

